# Generated by Django 5.1.1 on 2024-09-20 11:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialAssistanceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_status', models.CharField(max_length=100)),
                ('family_members', models.IntegerField(default=0)),
                ('personal_card', models.ImageField(upload_to='FinancialAssistanceRequest/personal_cards/')),
                ('proof_of_residence', models.ImageField(upload_to='FinancialAssistanceRequest/proof_of_residence/')),
                ('income', models.ImageField(blank=True, null=True, upload_to='FinancialAssistanceRequest/income/')),
                ('request_date', models.DateField(auto_now_add=True)),
                ('status_of_request', models.CharField(default='pending', max_length=100)),
                ('refugee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FinancialAssistanceResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_of_request', models.CharField(max_length=100, null=True)),
                ('financial_assistance_help', models.IntegerField(default=0)),
                ('response_date', models.DateField(auto_now_add=True)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='financial_help.financialassistancerequest')),
            ],
        ),
    ]
